# To adapt from ImThemes, change all "rgba(...)" to [...]
# Fork of Rounded Visual Studio style from ImThemes
alpha = 1.0
disabledAlpha = 0.4000000059604645
windowPadding = [8.0, 8.0]
windowRounding = 4.0
windowBorderSize = 0.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 3.799999952316284
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 2.5
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 11.0
scrollbarRounding = 2.5
grabMinSize = 10.0
grabRounding = 2.0
tabRounding = 3.5
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = [255, 255, 255, 1.0]
TextDisabled = [151, 151, 151, 1.0]
WindowBg = [37, 37, 38, 1.0]
ChildBg = [37, 37, 38, 1.0]
PopupBg = [37, 37, 38, 1.0]
Border = [78, 78, 78, 1.0]
BorderShadow = [78, 78, 78, 1.0]
FrameBg = [51, 51, 55, 1.0]
FrameBgHovered = [29, 151, 236, 1.0]
FrameBgActive = [0, 119, 200, 1.0]
TitleBg = [37, 37, 38, 1.0]
TitleBgActive = [37, 37, 38, 1.0]
TitleBgCollapsed = [37, 37, 38, 1.0]
MenuBarBg = [51, 51, 55, 1.0]
ScrollbarBg = [51, 51, 55, 1.0]
ScrollbarGrab = [82, 82, 85, 1.0]
ScrollbarGrabHovered = [90, 90, 95, 1.0]
ScrollbarGrabActive = [90, 90, 95, 1.0]
CheckMark = [0, 119, 200, 1.0]
SliderGrab = [29, 151, 236, 1.0]
SliderGrabActive = [0, 119, 200, 1.0]
Button = [51, 51, 55, 1.0]
ButtonHovered = [29, 151, 236, 1.0]
ButtonActive = [29, 151, 236, 1.0]
Header = [51, 51, 55, 1.0]
HeaderHovered = [29, 151, 236, 1.0]
HeaderActive = [0, 119, 200, 1.0]
Separator = [78, 78, 78, 1.0]
SeparatorHovered = [78, 78, 78, 1.0]
SeparatorActive = [78, 78, 78, 1.0]
ResizeGrip = [37, 37, 38, 1.0]
ResizeGripHovered = [51, 51, 55, 1.0]
ResizeGripActive = [82, 82, 85, 1.0]
Tab = [37, 37, 38, 1.0]
TabHovered = [29, 151, 236, 1.0]
TabActive = [0, 119, 200, 1.0]
TabUnfocused = [37, 37, 38, 1.0]
TabUnfocusedActive = [0, 119, 200, 1.0]
PlotLines = [0, 119, 200, 1.0]
PlotLinesHovered = [29, 151, 236, 1.0]
PlotHistogram = [0, 119, 200, 1.0]
PlotHistogramHovered = [29, 151, 236, 1.0]
TableHeaderBg = [48, 48, 51, 1.0]
TableBorderStrong = [79, 79, 89, 1.0]
TableBorderLight = [58, 58, 63, 1.0]
TableRowBg = [0, 0, 0, 0.0]
TableRowBgAlt = [255, 255, 255, 0.05999999865889549]
TextSelectedBg = [0, 119, 200, 1.0]
DragDropTarget = [37, 37, 38, 1.0]
NavHighlight = [37, 37, 38, 1.0]
NavWindowingHighlight = [255, 255, 255, 0.699999988079071]
NavWindowingDimBg = [204, 204, 204, 0.2000000029802322]
ModalWindowDimBg = [37, 37, 38, 1.0]